### ISSUE TITLE
Can't test with LFW full dataset

### ISSUE THREAD

**Issue by erdalalim** [TessFerrandez/research-papers#4]
Hi Tess,
Iam trying to run FaceNet.ipynb with LFW dataset..
But when Iam using full LFW dataset or more than 299 persons, In progressbar section  I meet error:

`12     img = align_image(img)
     13     # scale RGB values to interval [0,1]
---> 14     img = (img / 255.).astype(np.float32)
     15     # obtain embedding vector for image
     16     embedded[i] = nn4_small2_pretrained.predict(np.expand_dims(img, axis=0))[0]

TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
`
When Iam trying with less dataset it works properly.
How I can solve this, can you give me any suggestions?

**Comment by TessFerrandez** [comment]
That means exactly what the message says, that your image is None - hard to say why, probably something wrong with the data, maybe a corrupt image.

**Comment by erdalalim** [comment]
Yeah right,there is a problem with some images. I re-downloaded the dataset but still facing same problem. I have to find them manualy.
According to face clustering visualization, I didnt understand axis numbers. What they means exatcly.? 
I researched in OpenFace also, but there is no any explanation about this.

**Comment by saadnajib** [comment]
I had the similar issue with my dataset, it turns out that in some images dlib.get_frontal_face_detector() couldn't detect any faces  therefore img = align_image(img) this function returns Nonetype image (since no bounding box was found for aligning the image).
for this problem I cropped the images in my dataset focusing on only the face area and then passed the whole image coordinates instead of "bb" in this function "align_image(img)" and it worked fine.
